### ISSUE TITLE
error notice: recipient is not a valid field

### ISSUE THREAD

**Issue by jojo12** [betweenbrain/Custom-Contact-Form-Plugin#2]
Hi, I tried your two plugins custom-contact-form-plugin and email additional fields.
I enabled them and filled the contact form. When I clicked send, I got the above message and the field was in red.

**Comment by betweenbrain** [comment]
Hello,

Did you use the release from https://github.com/betweenbrain/Custom-Contact-Form-Plugin/releases or did you clone the `develop` branch for testing this?

**Comment by jojo12** [comment]
Hi, after reinstalling your release, the form works best. (now will try with email additional). Thanks. Will study more.

**Comment by betweenbrain** [comment]
Great! I will close this issue then. Please open a new one if you have any questions or problems with it.
